language: python
python:
  - "3.6"

branches:
  only:
  - master

script:
- |
  git config user.name "travis-ci-build"
  git config user.email "travis.ci.build@gmail.com"
  git remote remove origin
  git remote add origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  # darf auch failen, mal testen
  git push -d origin gh-pages
  git checkout -b gh-pages
  sphinx-build -b html docs docs/_build
  git add -A
  git commit -m "Update Sphinx"
  git push origin gh-pages
