language: python
python:
  - "3.6"

branches:
  only:
  - master

jobs:
  include:
    - stage: pylint
      name: "Unit Tests"
      script: pylint src
      script: black --check src
    - stage: deploy
      name: "Deploy to ADADADA"
      script:
      - |
        set -e
        git config user.name "traviscibot"
        git config user.email "deploy@travis-ci.org"
        git remote remove origin
        git remote add origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        git push -d origin gh-pages || true
        git checkout -b gh-pages
        sphinx-build -b html docs docs/_build
        git add -A
        git commit -m "Update Sphinx"
        git push origin gh-pages
