language: python
python:
  - "3.6"

jobs:
  include:
    - stage: test
      name: "Pylint static code analysis"
      script: pylint src
    - stage: test
      name: "Black code formatter"
      script: black --check src
    - stage: test
      name: "Sphinx docs generator"
      script: sphinx-build -b html docs docs/_build
    - stage: deploy
      name: "Deploy docs to GitHub"
      script:
      - |
        #!/bin/bash
        set -e
        if [ "${TRAVIS_PULL_REQUEST}" != "false" ]
        then
          printf '%s\n' "No deployment for pull requests"
          travis_terminate 0
        fi
        if [ "${TRAVIS_BRANCH}" != "master" ]
        then
          printf '%s\n' "No deployment for branches other than master"
          travis_terminate 0
        fi
        git config user.name "traviscibot"
        git config user.email "deploy@travis-ci.org"
        git remote remove origin
        git remote add origin "https://${GaITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
        git push -d origin gh-pages || true
        git checkout -b gh-pages
        sphinx-build -b html docs docs/_build
        git add -A
        git commit -m "Update docs"
        git push origin gh-pages
